spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.17.107:3306/aop?serverTimezone=GMT%2b8&characterEncoding=utf8&useUnicode=true&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: Nju123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      basePath: /api
  jackson:
    default-property-inclusion: non_null
#  redis:
#    host: 127.0.0.1
#    port: 6379
server:
  servlet:
    context-path-path: /aop